---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      cpus: 1
      memory: 1024


suites:
- name: default
  run_list: ["recipe[bitstarter-box]", "recipe[minitest-handler]" ]
  attributes: 
   bitstarter_box: 
      user:  "vagrant"
      group: "vagrant"
      bitstarter_app:
        git_repo: "https://github.com/skarab7/bitstarter.git"
        install_directory: "workspace/bitstarter"
        reference: master
