---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu-12.04

suites:
- name: default
  run_list: ["recipe[bitstarter-box-cookbook]", "recipe[minitest-handler]" ]
  attributes: 
   bitstarter_box_cookbook: 
      user:  "vagrant"
      group: "vagrant"
